spring:
  profiles:
    active: dev
  application:
    name: tamingo
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  mail:
    host: ${SMTP_HOST}
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jwt:
  secret: ${JWT_SECRET}
  access-exp-ms: 3600000        # 1시간
  refresh-exp-ms: 1209600000    # 14일

chatgpt:
  url: https://api.openai.com/v1
  api-key: ${GPT_API_KEY}

kakao:
  api:
    key: ${KAKAO_API_KEY}
    url: https://dapi.kakao.com

odsay:
  url: https://api.odsay.com/v1/api
  api-key: ${ODSAY_API_KEY}
  search-type: 0
  search-path-type: 0
  opt: 0

# service-region:
#   min-lat: 0.0
#   max-lat: 0.0
#   min-lng: 0.0
#   max-lng: 0.0